In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print(a[a>5])


[6 7 8 9]


In [8]:
valorAplicado = np.array([5000, 6000, 7000, 8000])
taxaJuros = np.array([1, 2, 3, 4])
resultado = valorAplicado * taxaJuros
resultado

array([ 5000, 12000, 21000, 32000])